server:
  port: 8888
  
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/redsky21/git-msa-local-repo.git

#          uri: file://C:\mywork\msa\git-msa-local-repo
